
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./staticfiles: /app/staticfiles # Bind mount

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edge_stream_db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: /nginx   # Build from nginx folder
    ports:
      - "80:80"
    depends_on:
      - backend    
volumes:
  postgres_data: