# Generated by Django 6.0.7 on 2026-08-02 11:12

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_poster_url', models.URLField()),
                ('movie_description', models.TextField()),
                ('movie_video_url', models.URLField()),
                ('movie_cast', models.JSONField(default=list)),
                ('movie_duration', models.FloatField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('average_engagement', models.FloatField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=10)),
            ],
        ),
    ]
