# Generated by Django 6.0.7 on 2026-08-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_genre_moviemodel_created_at_remove_moviemodel_genres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemodel',
            old_name='movie_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='movie_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='movie_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='movie_cast',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='movie_poster_url',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='movie_video_url',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
