# Generated by Django 6.0.7 on 2026-08-11 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_movie_description_moviemodel_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movieclick',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_click_constraint'),
        ),
    ]
