# Generated by Django 6.0.7 on 2026-08-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movieclick_unique_click_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='poster_url',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='video_url',
            field=models.CharField(blank=True),
        ),
    ]
