# Generated by Django 6.0.7 on 2026-08-16 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 16, 16, 6, 57, 988643, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
