# Generated by Django 6.0.7 on 2026-08-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_last_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
