
events {
    # configuration of connection processing
    worker_connections 1024;
}

http {
    # Configuration specific to HTTP and affecting all virtual servers
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name edge-stream; # Request to /edge-stream will be redirected to this server

        # React frontend
        root /var/www/frontend;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Pass backend request to django server
        location /backend {
            proxy_pass http://backend:8000/; # Use the container/service name, not 127.0.0.1

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
