name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: "True"

  DATABASE_NAME: ${{ vars.DATABASE_NAME }}
  DATABASE_USER: ${{ vars.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_HOST: ${{ vars.DATABASE_HOST }}
  DATABASE_PORT: ${{ vars.DATABASE_PORT }}

  AWS_STORAGE_BUCKET_NAME: ${{ vars.AWS_STORAGE_BUCKET_NAME }}
  AWS_S3_REGION_NAME: ${{ vars.AWS_S3_REGION_NAME }}

  EMAIL_BACKEND: ${{ vars.EMAIL_BACKEND }}
  EMAIL_HOST: ${{ vars.EMAIL_HOST }}
  EMAIL_PORT: ${{ vars.EMAIL_PORT }}
  EMAIL_USE_TLS: ${{ vars.EMAIL_USE_TLS }}
  EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  DEFAULT_FROM_EMAIL: ${{ vars.DEFAULT_FROM_EMAIL }}

  FRONT_END_DOMAIN: ${{ vars.FRONT_END_DOMAIN }}

  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  EC2_IP: ${{ vars.EC2_IP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test
        run: echo "GitHub Actions is working!"
      
      - name: Write pem file
        run: |
          echo "${{ secrets.MY_PEM_KEY }}" > private_key.pem
          chmod 600 private_key.pem


      - name: Deploy to EC2
        run: 
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@"$EC2_IP" << 'EOF'
            set -e

            cd /home/ubuntu/edge-stream

            echo "Pulling latest code..."
            git pull origin main

            echo "Building frontend..."
            cd frontend
            npm run build

            echo "Copying frontend files..."
            sudo rm -rf /var/www/frontend/*
            sudo cp -r dist/* /var/www/frontend/

            echo "Building and starting Docker containers..."
            cd ..
            docker compose up -d --build

            echo "Reloading Nginx..."
            sudo systemctl reload nginx

            echo "Deployment completed successfully!"
          EOF

          rm -f ec2-key.pem